cache:
  paths:
    - vendor/

before_script:
  - composer install
  - cp env.txt .env
  # Generate an application key. Re-cache.
  - php artisan key:generate
  - php artisan config:cache
  # Run database migrations.
  - php artisan migrate
  # Run database seed
  - php artisan db:seed

stages:
  - build

build:
  stage: build
  image: alpine
  script:
    - ls -la
    - cp -R /home/devzr01s/public_html/babaChicken/dev/public/media /home/devzr01s/public_html/babaChicken/backup/media
    - rm -rf /home/devzr01s/public_html/babaChicken/dev
    - pwd
    # - ls -la
    - cd ..
    - cp -R web /home/devzr01s/public_html/babaChicken/dev
    - cp -R /home/devzr01s/public_html/babaChicken/backup/media /home/devzr01s/public_html/babaChicken/dev/public
    - rm -rf /home/devzr01s/public_html/babaChicken/backup/media
    - cd /home/devzr01s/public_html/babaChicken/dev
    - pwd
    - composer dump-autoload
    - php artisan config:cache && php artisan cache:clear
    - find . -type f -exec chmod 644 {} \; && find . -type d -exec chmod 755 {} \;
    - chmod -R 777 storage
